on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of service/web app repository'
        required: false
        type: string
 #     secrets:
 #       required: true
      service_nama:
        description: 'ngetes tulisan wahahaaha'
        required: false
        type: string


env:
#  untuk default isi dengan nama repo
#  SERVICE_NAME: ${{ inputs.service_name || github.event.repository.name  }}
  SERVICE_NAME: ${{ inputs.service_name || 'ga masuk'  }}
  SERVICE_NAMA: ${{ inputs.service_nama || 'Wehehe'  }}


jobs:
  hitung:
    runs-on: ubuntu-latest
    steps:
      - id: menghitung
        name: menghitung 2+3
        run: echo ${2+3}
  baca:
    runs-on: ubuntu-latest
    steps:
      - id: membaca_with
        name: read with caller kalau dari env wahahaaha kalau bukan Wehehe
        run: echo ${{ inputs.service_nama }}

