on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of service/web app repository'
        required: false
        type: string
      secrets:
        required: true


env:
#  untuk default isi dengan nama repo
#  SERVICE_NAME: ${{ inputs.service_name || github.event.repository.name  }}
  SERVICE_NAME: ${{ inputs.service_name || 'ga masuk'  }}

jobs:
  hitung:
    runs-on: ubuntu-latest
    steps:
      - id: menghitung
        name: menghitung 2+3
        run: echo 2+3