on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of service/web app repository'
        required: false
        type: string

env:
#  untuk default isi dengan nama repo
#  SERVICE_NAME: ${{ inputs.service_name || github.event.repository.name  }}
  SERVICE_NAME: ${{ inputs.service_name || 'ga masuk'  }}


jobs:
  define:
    runs-on: ubuntu-latest
    outputs: 
      nama_runner: ${{ steps.declarerunner.outputs.value }}
    steps:
      - id: declarerunner
        run: |
          if ${{startsWith(inputs.runner_os, 'ubuntu')}}
          then
            echo "::set-output name=value::ubuntu-latest"
            echo "::notice title=runner::ubuntu-latest"
          elif ${{startsWith(inputs.runner_os, 'macos')}}
          then
            echo "::set-output name=value::macos-latest"
            echo "::notice title=runner::macos-latest"
          fi

  broadcast:
    needs: define
    runs-on: ${{ jobs.define.outputs.nama_runner}}
    steps:
      - name: input to variable service_name
        id: naming 
        run: echo "name=tags::docker_hub/${{ env.SERVICE_NAME }}:${GITHUB_REF#refs/*/}" 

      - name: read variable service_name
        id: read 
        run: echo "::notice title=naming tag created::${{ steps.naming.outputs.tags }}" 
